# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  push:

jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          check_artifacts:  true

      - name: Step 1 - Create a temporary artifact downloads folder
        run: mkdir downloads

      - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alpha'    > alpha.html
          echo 'bravo'    > bravo.html
          echo 'charlie'  > charlie.html
          cd ..

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets-for-download
          path: downloads
